server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-peer1:8761/eureka
spring:
  application:
    name: gateway
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
management:
  endpoints:
    web:
      exposure:
        include: '*'